package com.samil.dc.sql;

public class AppLogMngSQL {
	public static final String INSERT_LOG = "INSERT INTO LOG_MASTER(SYSTEMCODE,KIND,CURDB,CURDOC,EMPNO,USERID,CURUSER,MILEAGE,LOS,DEPARTMENT,DATETIME,DATEUNIT,TIMEUNIT)"
			+ " SELECT <#PRGCD#> SYSTEMCODE, <#KIND#> KIND, <#CURDB#> CURDB, <#CURDOC#> CURDOC, emplno EMPNO, inteid USERID, noteid CURUSER, '1' MILEAGE, loscd LOS, teamcd DEPARTMENT, SYSDATE DATETIME, TO_CHAR(SYSDATE, 'YYYYMMDD') DATEUNIT, TO_CHAR(SYSDATE, 'HH24MiSS') TIMEUNIT "
			+ " FROM NMSP.HREMP WHERE emplno = <#EMPLNO#>";
}
