package com.samil.dc.sql;

public class ApplicationGlobalSQL {
	public static final String SELECT_NAVIGATOR = ""
			+ " SELECT PATH, "
			+ "        SUBNM, "
			+ "        ID, "
			+ "        P_ID "
			+ "   FROM "
			+ "        (SELECT T.TABCD||'/'||S.SUBCD||'.jsp' AS PATH, "
			+ "               S.SUBNM AS SUBNM, "
			+ "               TO_NUMBER(T.SEQ||'000') + TO_NUMBER(S.SEQ) AS ID, "
			+ "               TO_NUMBER(T.SEQ||'000') AS P_ID, "
			+ "               S.TABCD||','||S.SUBCD AS A_CODE "
			+ "          FROM AUTH_TCODE T, "
			+ "               AUTH_SCODE S "
			+ "         WHERE T.PRGCD = <#SYSTEM_CODE#> "
			+ "               AND T.PRGCD = S.PRGCD "
			+ "               AND T.TABCD = S.TABCD "
			+ "            UNION "
			+ "        SELECT T.TABCD||'.jsp' AS PATH, "
			+ "               T.TABNM  AS SUBNM, "
			+ "               TO_NUMBER(T.SEQ||'000') AS ID, "
			+ "               TO_NUMBER(0||'0000') AS P_ID, "
			+ "               T.TABCD AS A_CODE "
			+ "          FROM AUTH_TCODE T "
			+ "         WHERE T.PRGCD = <#SYSTEM_CODE#> "
			+ "        ) M "
			+ "  WHERE(SELECT DISTINCT AUTHORITY_TYPE AS CHK "
			+ "          FROM HREMP B, "
			+ "               APP_AUTHORITY A "
			+ "         WHERE A.SYSTEM_CODE = <#SYSTEM_CODE#> "
			+ "               AND "
			+ "               ( "
			+ "                   (A.AUTHORITY_TARGET = B.EMPLNO AND TARGET_TYPE='E') "
			+ "                   OR (A.AUTHORITY_TARGET = B.TEAMCD AND TARGET_TYPE='T')"
			+ "                   OR (A.AUTHORITY_TARGET = B.GRADCD AND TARGET_TYPE='G')"
			+ "                   OR (A.AUTHORITY_DEVISION >= <#AUTHORITY_DEVISION#> AND TARGET_TYPE='M')"
			+ "               ) "
			+ "               AND B.INTEID = <#INTEID#> "
			+ "               AND B.OFFIST = '001' "
			+ "               AND A.PROGRAM_CODE = '0,'||M.A_CODE "
			+ "        ) IS NOT NULL "
			+ " ORDER BY ID ASC ";
	
	
	// EMPLNO
	public static final String SELECT_USERINFO_BY_EMPLNO = " SELECT H.PRTDV AS PTRDV, "
			+ "        H.INTEID, "
			+ "        H.EMAIL, "
			+ "        H.EMPLNO, "
			+ "        H.KORNM, "
			+ "        H.ENGNM, "
			+ "        H.GRADCD, "
			+ "        H.LOSCD, "
			+ "        H.TEAMCD, "
			+ "        H.APPCD, "
			+ "        T.TEAMNM, "
			+ "        G.GRADNM, "
			+ "        W.APP AS APPNM, "
			+ "        C.ETCDNM AS LOSNM, "
			+ "        H.PHOEXT "
			+ "   FROM CMTEAMCD T, "
			+ "        HRGRAD G, "
			+ "        CMETCOCD C, "
			+ "        HRTRANWRK W, "
			+ "        HREMP H "
			+ "  WHERE H.EMPLNO = <#EMPLNO#> "
			+ "        AND H.OFFIST = '001' "
			+ "        AND H.GRADCD = G.GRADCD "
			+ "        AND H.TEAMCD = T.TEAMCD "
			+ "        AND H.LOSCD = C.ETCOCD "
			+ "        AND C.SYTMDV = 'CM' "
			+ "        AND H.OFFIST = '001' "
			+ "        AND C.CLASCD = '06' "
			+ "        AND H.EMPLNO = W.EMSABUCD";
	
	
	//USERID
	public static final String SELECT_USERINFO_BY_USERID = " SELECT H.PRTDV AS PTRDV, "
			+ "        H.INTEID, "
			+ "        H.EMAIL, "
			+ "        H.EMPLNO, "
			+ "        H.KORNM, "
			+ "        H.ENGNM, "
			+ "        H.GRADCD, "
			+ "        H.LOSCD, "
			+ "        H.TEAMCD, "
			+ "        H.APPCD, "
			+ "        T.TEAMNM, "
			+ "        G.GRADNM, "
			+ "        W.APP AS APPNM, "
			+ "        C.ETCDNM AS LOSNM, "
			+ "        H.PHOEXT "
			+ "   FROM CMTEAMCD T, "
			+ "        HRGRAD G, "
			+ "        CMETCOCD C, "
			+ "        HRTRANWRK W, "
			+ "        HREMP H "
			+ "  WHERE H.INTEID = <#USERID#> "
			+ "        AND H.OFFIST = '001' "
			+ "        AND H.GRADCD = G.GRADCD "
			+ "        AND H.TEAMCD = T.TEAMCD "
			+ "        AND H.LOSCD = C.ETCOCD "
			+ "        AND C.SYTMDV = 'CM' "
			+ "        AND H.OFFIST = '001' "
			+ "        AND C.CLASCD = '06' "
			+ "        AND H.EMPLNO = W.EMSABUCD";
	
	
	//SYSTEM_CODE, MENU_PATH, USERID 
	public static final String SELECT_USERINFO_WITH_AUTHORITY_BY_USERID = " SELECT NVL(A.AUTHORITY_TYPE, '') AS AUTH_TYPE, "
			+"        NVL(A.AUTHORITY_DEVISION, '') AS AUTH_CLASS, "
			+"        H.PRTDV AS PTRDV, "
			+"        E.AUTH AS AUTH_APP, "
			+"        H.INTEID, "
			+"        H.EMAIL, "
			+"        H.EMPLNO, "
			+"        H.KORNM, "
			+"        H.ENGNM, "
			+"        H.GRADCD, "
			+"        H.LOSCD, "
			+"        H.TEAMCD, "
			+"        H.APPCD, "
			+"        T.TEAMNM, "
			+"        G.GRADNM, "
			+"        W.APP AS APPNM, "
			+"        C.ETCDNM AS LOSNM, "
			+"        H.PHOEXT "
			+"   FROM CMTEAMCD T, "
			+"        HRGRAD G, "
			+"        CMETCOCD C, "
			+"        HRTRANWRK W, "
			+"        HREMP H LEFT JOIN APP_AUTHORITY A "
			+"        ON A.SYSTEM_CODE = <#SYSTEM_CODE#>"
			+"        AND "
			+"        ( "
			+"            A.AUTHORITY_TARGET = H.EMPLNO "
			+"            OR A.AUTHORITY_TARGET = H.TEAMCD "
			+"            OR A.AUTHORITY_TARGET = H.GRADCD  "
			+"        ) "
			+"        AND A.PROGRAM_CODE = '0'||<#MENU_PATH#> , "
			+"        (SELECT MIN(AUTH) AUTH "
			+"          FROM "
			+"               (SELECT decode(max(emplno),NULL,'4','0') AUTH " // 부대표 이상
			+"                 FROM "
			+"                      (SELECT a.emplno "
			+"                        FROM hremp a, "
			+"                             hrgrad b "
			+"                       WHERE a.inteid = <#USERID#> "
			+"                             AND a.offist = '001' "
			+"                             AND a.gradcd = b.gradcd "
			+"                             AND b.gradcd <= '005' "
			+"                      ) "
			+"                   UNION "
			+"               SELECT decode(max(emplno),NULL,'4','1') auth "	// 로스장
			+"                 FROM "
			+"                      (SELECT a.emplno "
			+"                        FROM hremp a, "
			+"                             CMETCOCD b "
			+"                       WHERE a.inteid= <#USERID#> "
			+"                             AND a.offist = '001' "
			+"                             AND b.SYTMDV = 'PM' "
			+"                             AND b.CLASCD = '30' "
			+"                             AND b.etcocd IN ('10', '20', '30', '40') "
			+"                             AND a.emplno = b.mgatt1 "
			+"                      ) "
			+"                   UNION "
			+"               SELECT decode(max(emplno),NULL,'4','2') auth "	// 본부장, 팀장
			+"                 FROM "
			+"                      (SELECT a.emplno "
			+"                        FROM hremp a, "
			+"                             CMTEAMCD b "
			+"                       WHERE a.inteid= <#USERID#> "
			+"                             AND a.offist = '001' "
			+"                             AND a.emplno = b.REPTEMP "
			+"                             AND b.UsesYN = 'Y' "
			+"                      ) "
			+"               ) "
			+"        ) E "
			+"  WHERE H.INTEID = <#USERID#> "
			+"        AND H.OFFIST = '001' "
			+"        AND H.GRADCD = G.GRADCD "
			+"        AND H.TEAMCD = T.TEAMCD "
			+"        AND H.LOSCD = C.ETCOCD "
			+"        AND C.SYTMDV = 'CM' "
			+"        AND H.OFFIST = '001' "
			+"        AND C.CLASCD = '06' "
			+"        AND H.EMPLNO = W.EMSABUCD";
	
}
